### ISSUE TITLE
Report, install on Arcolinux

### ISSUE THREAD

**Issue by naib864** [gardotd426/regolith-de#17]
Works almost perfect now! Used my own modified configs and looks for regolith from my main system and it worked almost out of the box. Only had to change some of the icons as the material design icons are somehow encoded different in the arch source? Not sure why. Other than that though, no issues yet. Awesome! Thank you for creating this pkgbuild :)

Will update this thread in case I run into some issues when using the system excessively within the next days.

**Comment by naib864** [comment]
Neofetch tells me the DE is gnome instead of regolith (Hyper important issue, fix asap!!!!11).
No seriously, the only issue I've ran into is that the rofi look doesn't change when changing the look.
When I tell rofi manually to use a theme, it works.

**Comment by gardotd426** [comment]
Rofi now changes its theme when you use `regolith-look` to set the look and feel. 

Package is now in the AUR. Check README for info. Closing.
