### ISSUE TITLE
Broken, lots of missing packages. 

### ISSUE THREAD

**Issue by lbibass** [gardotd426/regolith-de#18]
A significant amount of packages have been broken through updates. 

Revising the names should fix it.

**Comment by gardotd426** [comment]
Okay I'll handle it

**Comment by gardotd426** [comment]
Sorry I had to wait for my RMA on my RTX 3090 to get back because the 5800X has no integrated GPU, and I didn't feel like setting up Arch and all that on my old laptop I don't use anymore, but my card came in yesterday and it's all fixed now.

**Comment by lbibass** [comment]
> Sorry I had to wait for my RMA on my RTX 3090 to get back because the 5800X has no integrated GPU, and I didn't feel like setting up Arch and all that on my old laptop I don't use anymore, but my card came in yesterday and it's all fixed now.

Great! Thanks so much.

**Comment by lbibass** [comment]
Alright, one last issue. flashback.patch isn't there. 

```==> ERROR: flashback.patch was not found in the build directory and is not a URL.
```

**Comment by gardotd426** [comment]
Yeah, it's been removed. It's no longer necessary, because I filed an issue
with Ken (Regolith Linux creator) and he changed it to incorporate my
patch's changes. flashback.patch won't even apply anymore, because it's
already been "applied." Same with the other patches except one, I believe.
So no, that's not an issue

**Comment by lbibass** [comment]
Neat! Sounds good. It's just that it's still in the pkgbuild, so it's throwing an error. I can just remove it though.

**Comment by gardotd426** [comment]
Wait no, all the rest of the patches were removed, but flashback.patch is
still needed. My bad, hold up.
