### ISSUE TITLE
Early first issues building on a current machine

### ISSUE THREAD

**Issue by Strykar** [gardotd426/regolith-de#2]
I tried to install the package on my current Arch desktop and it fails because of 2 package groups:
```
==> Installing regolith-de package group with pacman -U...
loading packages...
resolving dependencies...
warning: cannot resolve "i3-status", a dependency of "regolith-i3"
warning: cannot resolve "xorg", a dependency of "regolith-i3"
warning: cannot resolve "xorg-apps", a dependency of "regolith-i3"
:: The following package cannot be upgraded due to unresolvable dependencies:
      regolith-i3

:: Do you want to skip the above package for this upgrade? [y/N] 	n
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'i3-status' required by regolith-i3
:: unable to satisfy dependency 'xorg' required by regolith-i3
:: unable to satisfy dependency 'xorg-apps' required by regolith-i3
==> WARNING: Failed to install built package(s).
```

So `i3-status` seems straightforward, it's called [i3status](https://www.archlinux.org/packages/community/x86_64/i3status/).
I already have `xorg` and `xorg-apps` installed so I'm unsure why these two warnings popup.

I'll try building and installing in a VM soon.

**Comment by gardotd426** [comment]
It's not that, I messed up is all. Go ahead and use the latest master and
try again. I forgot that you can't require package groups for dependencies
(I'd just done that as a temporary way to keep from having to put a bunch
of X11 deps in there but I think we can leave most of them out anyway).
xorg and xorg-apps aren't packages, they're package groups. So it can't
confirm whether you have them installed or not. I fixed it. In the latest
master.

**Comment by gardotd426** [comment]
Closed 9d5ce71

**Comment by Strykar** [comment]
Still has issues..

```
==> Installing regolith-de package group with pacman -U...
loading packages...
resolving dependencies...
warning: cannot resolve "i3-status", a dependency of "regolith-i3"
warning: cannot resolve "x11-xwininfo", a dependency of "regolith-i3"
warning: cannot resolve "xcb-uitl-image", a dependency of "regolith-i3"
warning: cannot resolve "xcb-util-renderutilkkkkkkkkkkkkkkkkkkkkkkkkkssss", a dependency of "regolith-i3"
:: The following package cannot be upgraded due to unresolvable dependencies:
      regolith-i3
```

**Comment by gardotd426** [comment]
come on man. That's obviously just a typo, you could have fixed that
yourself.

Either way. It's fixed now.
