### ISSUE TITLE
i3xrocks split into packages

### ISSUE THREAD

**Issue by paolomainardi** [gardotd426/regolith-de#26]
First of all, let me thank you a lot for this great project, having Regolith on Archlinux is uber cool.

What i've noticed for now is that i3xrocks is a full package containing all blocks available, that are a bit overwhelming, i shuold dig the packages more but just in case, is there a way to remove some of them ? I've installed this one:https://aur.archlinux.org/packages/regolith-full/

**Comment by gardotd426** [comment]
It only contains 16 blocks. There are way, way more than that available for i3blocks. 

Further, the full installed size of the entire `regolith-i3xrocks` package is only 77.9 KiB. It's 2021, 78 KiB is quite small. The package for `regolith-st` is bigger than that, and that's ***st***, a suckless-developed application. So I'm honestly really struggling with understanding where you get the sense that the package is too large or how it's overwhelming. If you could explain what you're talking about and how it's overwhelming I might consider doing something about it, but right now what you're saying makes no sense, it's not large from a size perspective.

**Comment by paolomainardi** [comment]
Further, since you are so aggressive, it is better if I stay away from this project at all.

**Comment by paolomainardi** [comment]
Well, maybe I’ve over reacted and so happy to have seen a progress in this area too.

Just an honest question, have you considered to open PRs against the origin to integrate the patches ? Like the flashback one.
