### ISSUE TITLE
Rofi icons

### ISSUE THREAD

**Issue by Ahanaf-Ether** [gardotd426/regolith-de#29]
Rofi icons not appearing.

**Comment by gardotd426** [comment]
Do you have a user `rofi.conf` config file that sets whether to show icons or not? Because only one of the Regolith Styles defines whether to show icons (Midnight). 

You can find out easily by `rofi -dump-config | grep icon`. 

Because I can't reproduce, I have icons here.

**Comment by Ahanaf-Ether** [comment]
Alright thanks I fixed it, btw great work!

**Comment by gardotd426** [comment]
Thanks! Closing
