### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by naib864** [gardotd426/regolith-de#8]
The regolith-st has some issues. Whenever I press backspace, it will move the cursor to the right. It deletes the last character but it will still be visible on screen.
For example: When I type "sudk", then press backspace and type "o", the screen will show "sudk o". When I press enter, sudo will be executed.

**Comment by JoshuaCrewe** [comment]
I get this too. I thought I borked it though but haven’t had the time to confirm that it was happenening.

**Comment by gardotd426** [comment]
Sorry guys, I had some weird crazy shit happen with my machine yesterday and I've been doing crisis mode for the last 24 hours, I'm just now getting some time to look at this. I'll look into it, and if we have to, I'll replace st with something else. 

I'm assuming other terminals don't show this behavior?

**Comment by naib864** [comment]
Other terminals are fine, yes.

**Comment by gardotd426** [comment]
I'm not sure what's going on, because I can't reproduce. 

I went and installed a fresh Manjaro KDE VM and installed regolith overtop of it, logged out and back in, and everything works as intended. ST is running, and backspace works fine...

**Comment by JoshuaCrewe** [comment]
@naib864 have you made any changes or added `~.Xresources` ? Have you used `regolith-look` to change theme at all ?

**Comment by gardotd426** [comment]
> @naib864 have you made any changes or added `~.Xresources` ? Have you used `regolith-look` to change theme at all ?

Regolith doesn't touch or read ~/.Xresources. It creates its own ~/.Xresources-regolith file with ftue/look (which literally just points to the theme directory file, which in turn points to the other necessary theme files) and reads that, and in the absence of ~/.Xresources-regolith, it uses the default lascaille regardless of whether there's an ~/.Xresources. I tested this on an already-running system (I just cloned my main daily driver Arch install and put it on another partition) which already had ~/.Xresources and ~/.config/i3/config files and all the other config files you can think of (my ~/.config was 2GB). 

I haven't actually tested changing a theme with `regolith-look`, but from what I saw it shouldn't be any different on Arch than on Regolith, it's just a little script. 

It *does* use `xrdb` so if you have things in your regular ~/.Xresources for i3xrocks or something (which I find unlikely) then yeah that could cause an issue. 

Note, also, @naib864 I saw you mention before that GNOME wasn't showing lascaille as the theme. It wouldn't. The theme names are entirely limited to regolith itself, they aren't GTK themes (which is what GNOME sees). Regolith instead has a specific GTK theme it uses with regolith-look, so when you choose a theme, it uses gsettings to change the GTK theme.
